### PR TITLE
a naive patch to set JMSTimestamp

### PR DESCRIPTION
**Pull request by bat-cha**
Using "SentTimestamp" as JMSTimestamp
see #20

### CODE REVIEW

**Comment by pranav8494** [comment]
@kuba-aws Any update on this PR?

**Comment by MrBuddyCasino** [comment]
This would be useful to have - any chances of getting this?

**Comment by pranav8494** [comment]
@kuba-aws Any update on merging this PR?

**Comment by alexmnyc** [comment]
Please fix!!!! Jms timestamp is always 0L, it's not acceptable

**Comment by vghero** [comment]
Any reason why this hasn't been merged yet?

**Comment by vghero** [comment]
Anyone?

**Review by eddy-aws — APPROVED** [review]

**Comment by volkanto** [comment]
already tackled in https://github.com/awslabs/amazon-sqs-java-messaging-lib/pull/111 thx @bat-cha

**Pull request closed without merging**
