### PR TITLE
Updating to latest version of Java SDK

### PR DESCRIPTION
**Pull request by shorea**

### CODE REVIEW

**Comment by shorea** [comment]
The testOneAck(com.amazon.sqs.javamessaging.RangedAcknowledgerTest) test was failing before and after this change.

**Comment by ttwd80** [comment]
@shorea any estimates when 1.0.1 will be released?

**Comment by jgangemi** [comment]
i would hope this version would be something along the lines of `2.0.0` given it's dealing w/ a breaking change.

**Comment by ziyanli-amazon** [comment]
staled

**Pull request closed without merging**
