### PR TITLE
Add a default ConnectionFactory constructor

### PR DESCRIPTION
**Pull request by gilbahat**
This is needed when there is no ability to change the code of an existing app, only to provide a factory class. Such apps cannot currently load the connector, because they call the default init method which doesn't exist.

the particular culprit is a healthcare processor called mirth connect (http://www.mirthproject.org/) , but I am sure this scenario could just as well apply to other products...

### CODE REVIEW

**Comment by gilbahat** [comment]
I forgot to submit a PR for this. bummer.

**Comment by gilbahat** [comment]
Hi @ziyanli-amazon ,

Thank you for picking up the maintenance of the library.
Even if stale, I would be happy to know why was this PR closed without being merged.

**Comment by ziyanli-amazon** [comment]
Hi @gilbahat ,
Sorry it was closed by mistake. I was going through some already staled PRs and close some of them. Can you resolve conflicts and I can take a look tomorrow afternoon.

**Comment by gilbahat** [comment]
Conflicts resolved

**Comment by ziyanli-amazon** [comment]
https://github.com/awslabs/amazon-sqs-java-messaging-lib/commit/f9bde2d629adda51f7fdd2af958af0dbe11a693c

**Pull request closed without merging**
