### PR TITLE
Preserve the JMS Correlation ID when sending and receiving messages

### LINKED ISSUE #19: JMSCorrelationId is null on receiver side
TextMessage's that have JMSCorrelationID set when received have null correlationId.

CorrelationID is useful for request/response patterns.

### PR DESCRIPTION
**Pull request by candrews**
Fixes #19

### CODE REVIEW

**Comment by candrews** [comment]
@robin-aws this is the PR we discussed on our call.

**Comment by robin-aws** [comment]
Thanks Craig. Looks good to me as this is an obvious bug (since setJMSCorrelationID() currently succeeds rather than throwing an exception). 

As I mentioned earlier, we are unfortunately not set up well to accept pull requests just yet, but I will make sure this makes it into the next release.

**Comment by candrews** [comment]
@robin-aws do you know when the next release may be?

**Comment by robin-aws** [comment]
Hi Craig. We don't have an ETA at the moment but we are about due for another release. I'll discuss with the team and get back to you in a day or two.

**Comment by sullis** [comment]
what is the status of this PR?

**Comment by robin-aws** [comment]
Hi sullis - I'm happy to say I have a solution to the build issues that makes it difficult for us to accept pull requests, and I'm implementing it this week. Once I'm confident it will work I'm happy to accept this PR and then quickly create a release for this and a few other lingering PRs. Thanks for your patience!

**Comment by candrews** [comment]
Another 5 weeks have passed...

**Comment by robin-aws** [comment]
Hi Craig. My apologies for the further delays. I've had some trouble with our integration tests that are blocking creating releases. In the meantime, though, I'm happy to at least accept this PR since it's very low risk.

**Pull request merged**
